Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -27,7 +27,21 @@ jobs:
         run: sudo apt-get update && sudo apt-get install httrack -y
 
       - name: Run yarn run dev
-        run: yarn run dev
+        run: yarn run dev &
+
+      - name: Wait for yarn run dev to start
+        run: sleep 10s
 
       - name: Run HTTrack
-        run: httrack --mirror http://localhost:2368 -O ./gh-pages
+        run: |
+          httrack --mirror http://localhost:2368 -O ./gh-pages
+          export HTTRACK_EXIT_CODE=$?
+          if [[ $HTTRACK_EXIT_CODE -eq 0 ]]; then
+            echo "HTTrack completed successfully"
+          else
+            echo "HTTrack failed with exit code: $HTTRACK_EXIT_CODE"
+          fi
+
+      - name: End process
+        run: |
+          kill $(pgrep -f "yarn run dev")
